
package ui;
    
import java.sql.*;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import src.DB;
import ui.Home;


public class Teacher extends javax.swing.JInternalFrame {

  
    DefaultTableModel dtm;
    String _ID = "";
    
    public Teacher() {
        initComponents();
        
        dtm = (DefaultTableModel)tbl_teacher.getModel();
        loadData();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_barcode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_adress = new javax.swing.JTextField();
        txt_bd = new javax.swing.JTextField();
        txt_tchr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_gender = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_teacher = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_filter = new javax.swing.JTextField();

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel7.setText("Student Name  :-");

        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        setClosable(true);
        setIconifiable(true);
        setTitle("Teacher Admission");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Teacher Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 16))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Barcode                  :-");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 35, 140, -1));

        txt_barcode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_barcodeActionPerformed(evt);
            }
        });
        jPanel2.add(txt_barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 32, 265, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Teacher Name         :-");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 79, 140, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Adress                    :-");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 120, 140, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Birthday                  :-");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 161, 140, -1));

        txt_adress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_adressActionPerformed(evt);
            }
        });
        jPanel2.add(txt_adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 117, 265, -1));

        txt_bd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bdActionPerformed(evt);
            }
        });
        jPanel2.add(txt_bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 158, 265, -1));

        txt_tchr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_tchr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tchrActionPerformed(evt);
            }
        });
        jPanel2.add(txt_tchr, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 76, 265, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel9.setText("Gender                   :-");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 200, 140, -1));

        txt_contact.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactActionPerformed(evt);
            }
        });
        jPanel2.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 240, 265, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Contact Number       :-");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 243, 140, -1));

        txt_gender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_genderActionPerformed(evt);
            }
        });
        jPanel2.add(txt_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 199, 265, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 80, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 70, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 440, 550));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Saved Teachers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        tbl_teacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Barcode", "Name", "Adress", "Birthday", "Gender", "Contact"
            }
        ));
        tbl_teacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_teacherMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_teacher);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Search   :-");

        txt_filter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filterActionPerformed(evt);
            }
        });
        txt_filter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_filterKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txt_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txt_filter)
                        .addGap(3, 3, 3)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 700, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 1170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            DB.getConnection().createStatement().executeUpdate("insert into teacher(barcode,name,adress,birthday,gender,contact) values('"+txt_barcode.getText()+"','"+txt_tchr.getText()+"','"+txt_adress.getText()+"','"+txt_bd.getText()+"','"+txt_gender.getText()+"','"+txt_contact.getText()+"')");
            JOptionPane.showMessageDialog(rootPane , "Data Saved Succesfully");
            loadData();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_genderActionPerformed

    private void txt_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactActionPerformed

    private void txt_tchrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tchrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tchrActionPerformed

    private void txt_bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bdActionPerformed

    private void txt_adressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_adressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_adressActionPerformed

    private void txt_barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_barcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_barcodeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    try {
            
            int selection = JOptionPane.showConfirmDialog(rootPane,"want to delete current data");
            if (selection == 0){
                
                DB.getConnection().createStatement().executeUpdate("delete from teacher where id='"+_ID+"'");
                JOptionPane.showMessageDialog(rootPane, "Data Deleted");
                loadData();
            
            }
            
            
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            
            int selection = JOptionPane.showConfirmDialog(rootPane,"want to change current data");
            if (selection == 0){
                
                DB.getConnection().createStatement().executeUpdate("update teacher set barcode = '"+txt_barcode.getText()+"' , name = '"+txt_tchr.getText()+"' , adress = '"+txt_adress.getText()+"' , birthday = '"+txt_adress.getText()+"' , birthday = '"+txt_bd.getText()+"' , gender = '"+txt_gender.getText()+"' , contact = '"+txt_contact.getText()+"' where id = '"+_ID+"' ");
                JOptionPane.showMessageDialog(rootPane, "Data Updated");
                loadData();
            
            }
            
            
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbl_teacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_teacherMouseClicked
        int selected_row = tbl_teacher.getSelectedRow();
        txt_barcode.setText(dtm.getValueAt(selected_row, 1).toString());
        txt_tchr.setText(dtm.getValueAt(selected_row, 2).toString());
        txt_adress.setText(dtm.getValueAt(selected_row, 3).toString());
        txt_bd.setText(dtm.getValueAt(selected_row, 4).toString());
        txt_gender.setText(dtm.getValueAt(selected_row, 5).toString());
        
        txt_contact.setText(dtm.getValueAt(selected_row, 6).toString());
        
        _ID = dtm.getValueAt(selected_row, 0).toString();
    }//GEN-LAST:event_tbl_teacherMouseClicked

    private void txt_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filterActionPerformed

    private void txt_filterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filterKeyReleased
         filter_table(txt_filter.getText().toUpperCase());
    }//GEN-LAST:event_txt_filterKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTable tbl_teacher;
    private javax.swing.JTextField txt_adress;
    private javax.swing.JTextField txt_barcode;
    private javax.swing.JTextField txt_bd;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_filter;
    private javax.swing.JTextField txt_gender;
    private javax.swing.JTextField txt_tchr;
    // End of variables declaration//GEN-END:variables
      
void loadData(){
            try {
                dtm.setRowCount(0);
                ResultSet rs  = DB.getConnection().createStatement().executeQuery("select * from teacher");
                
                
                while(rs.next()){
                    Vector v = new Vector();
                    v.add(rs.getString("id").toUpperCase());
                    v.add(rs.getString("barcode").toUpperCase());
                    v.add(rs.getString("name").toUpperCase());
                    v.add(rs.getString("adress").toUpperCase());
                    v.add(rs.getString("birthday").toUpperCase());
                    v.add(rs.getString("gender").toUpperCase());                   
                    v.add(rs.getString("contact").toUpperCase());
                    
                    dtm.addRow(v);
                    
                }
            } catch (Exception e) {
                e.printStackTrace();
            
            }
 
       
        
}

void filter_table(String query){
        
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<DefaultTableModel>(dtm);
        tbl_teacher.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(query));
        
        
    }



}
